name: Testing through Building  

on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create dummy .env file
        run: |
          echo "SUPABASE_URL=https://example.supabase.co" >> .env
          echo "SUPABASE_ANON_KEY=dummy" >> .env
          echo "DATABASE_URL=postgresql://user:password@localhost:5432/db" >> .env
          echo "DIRECT_URL=postgresql://user:password@localhost:5432/db" >> .env

      - name: Install dependencies
        run: npm install

      - name: Running Lint
        run: npm run lint

      - name: Build project
        run: npm run build
