name: Mirror Repository

on:
  push:
    branches:
      - '**' # This now triggers on a push to any branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to mirror
        run: git push --mirror https://miraibitselectronics:${{ secrets.MIRROR_REPO_PAT }}@github.com/miraibitselectronics/miraibits-frontend-nextjs.git
